labtest_8: lab_7_unit_test.o lab_7.o 
	g++ -Wall -g -o labtest lab_7.o lab_7_unit_test.o 
	
lab_7: lab_7.cpp
	g++ -Wall -g -c lab_7.cpp

unittest8: lab_7_unit_test.cpp
	g++ -Wall -g -c lab_7_unit_test.cpp

clean:
	rm *.o *test