labtest_8: lab_8_unit_test.o lab_8.o 
	g++ -Wall -g -o labtest_8 lab_8.o lab_8_unit_test.o 
	
lab_8: lab_8.cpp
	g++ -Wall -g -c lab_8.cpp

unittest8: lab_8_unit_test.cpp
	g++ -Wall -g -c lab_8_unit_test.cpp

clean:
	rm *.o *test